pipeline {
    agent any

    stages {
        stage('Fetch and Push to GitHub') {
            steps {
                script {
                    // Define the paths to your local Git repository and the remote GitHub repository.
                    def localRepoPath = 'C:\\PoC1'
                    def githubRepoURL = 'https://github.com/nikithajoyce23/PoC1.git'

                    // Check if changes exist in the local Git repository.
                    def hasChanges = false

                    dir(localRepoPath) {
                        // Use 'git diff --exit-code' to return non-zero if changes exist.
                        hasChanges = bat(script: 'git diff --exit-code', returnStatus: true) != 0

                        if (hasChanges) {
                            echo 'Changes detected'

                            // Fetch changes from the local repository and push to GitHub.
                            bat(script: 'git config --global --add safe.directory C:/PoC1')
                            bat(script: 'git add .')
                            bat(script: 'git commit -m "Auto-commit: Changes detected"')
                            bat(script: 'git push origin main')  // Adjust 'main' to your branch name if needed
                        } else {
                            echo 'No changes'
                        }
                    }
                }
            }
        }
    }
}